resolver: nightly-2017-02-28
packages:
- .
- store-core
- location: deps/weigh
  extra-dep: true
- location:
    git: https://github.com/sjakobi/containers
    commit: 53e82d93c7aa58f6a00c2364ffa9dd2dd7b376e9
  extra-dep: true
extra-deps:
- criterion-1.1.4.0
- cassava-0.4.5.1
